services:

  deliver.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: deliver.db
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_SA_PASSWORD=12345678Dd@
    ports:
      - "1400:1433"
    volumes:
      - ./.containers/deliver-db/data:/var/opt/mssql/data
      - ./.containers/deliver-db/log:/var/opt/mssql/log
      - ./.containers/deliver-db/secrets:/var/opt/mssql/secrets