name: CI/CD Pipeline
on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: cicd
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t deliver.api .

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker ps
            docker stop deliver.api || true
            docker rm deliver.api || true

            container_id=$(docker ps -q --filter "publish=8080")
            if [ ! -z "$container_id" ]; then
            docker stop $container_id
            docker rm $container_id
            fi
            
            fuser -k 8080/tcp || true
            docker run -d --name deliver.api -p 8080:8080 deliver.api
